title: CodingLabs
subtitle: keep coding, keep foolish
link: http://blog.codinglabs.org
meta:
  description: keep coding, keep foolish
  keywords: !!seq
    - 代码
    - 数学
    - 数据挖掘
    - 机器学习
    - 算法
    - 编译器
    - 分布式
    - PHP
    - Nginx
  author: 张洋
master:
  name: 张洋
  about: 又一个程序猿（codemonkey <span style="color:#999;">/koʊdˈmʌŋki/</span>），<a href="/pages/about-me.html">更多...</a>
  email: ericzhang.buaa@gmail.com
  weibo: ericzhangbuaa
rss:
  title: CodingLabs
  desc: keep coding, keep foolish
  lang: zh-cn
  max: 10
copyright:
  owner: CodingLabs
  beginYear: 2011
  endYear: 2013
  ICP: 京ICP备12043064-1号
theme: default
